nextcloud:
  url: "https://***REMOVED_DUCKDNS_URL***/"
  username: "admin"
  password: "default_password"  

proxmox:
  - host: "***REMOVED_PROXMOX_IP_1***"
    username: "root@pam"
    password: "default_password"  
    verify_ssl: false
  - host: "***REMOVED_PROXMOX_IP_2***"
    username: "root@pam"
    password: "default_password"  
    verify_ssl: false