nextcloud:
  url: "https://yn3143.duckdns.org/"
  username: "admin"
  password: "default_password"  # 環境変数 NEXTCLOUD_PASSWORD で上書き可能

proxmox:
  - host: "192.168.0.102"
    username: "root@pam"
    password: "default_password"  # 環境変数 PROXMOX_PASSWORD_1 で上書き可能
    verify_ssl: false
  - host: "192.168.0.101"
    username: "root@pam"
    password: "default_password"  # 環境変数 PROXMOX_PASSWORD_2 で上書き可能
    verify_ssl: false