nextcloud:
  url: "${NEXTCLOUD_URL}"
  username: "${NEXTCLOUD_USERNAME}"
  password: "${NEXTCLOUD_PASSWORD}"

proxmox:
  - host: "${PROXMOX_HOST_1}"
    username: "${PROXMOX_USERNAME}"
    password: "${PROXMOX_PASSWORD}"
    verify_ssl: false
  - host: "${PROXMOX_HOST_2}"
    username: "${PROXMOX_USERNAME}"
    password: "${PROXMOX_PASSWORD}"
    verify_ssl: false
