nextcloud:
  url: "https://yn3143.duckdns.org/"
  username: "admin"
  password: "Uyan3143?!"

proxmox:
  - host: "192.168.0.102"
    username: "root@pam"
    password: "Uyan3143?!"
    verify_ssl: false
  - host: "192.168.0.101"
    username: "root@pam"
    password: "Uyan3143?!"
    verify_ssl: false
