name: Deploy to Home Server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy via SSH to custom port
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.HOME_SERVER_IP }}
          username: ${{ secrets.HOME_SERVER_USER }}
          key: ${{ secrets.HOME_SERVER_SSH_KEY }}
          port: 2222
          script: |
            echo "[*] Switching to project directory"
            cd ~/MONITORING-API

            echo "[*] Pulling latest code"
            git pull origin main

            echo "[*] Restarting Python Flask API"
            screen -S api -X quit || true
            screen -dmS api python3 main.py

            echo "[*] Restarting Node.js Server"
            cd monitor
            npm install
            screen -S monitor -X quit || true
            screen -dmS monitor node server.js
